name: "Terraform EKS Setup"

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/**'

jobs:
  setup-eks-cluster:
    name: Setup EKS Cluster
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        folder: ['eks_cluster', 'addons']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform -chdir=${{matrix.folder}} init

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'push'
      run: terraform -chdir=${{ matrix.folder }} plan -no-color
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform -chdir=${{ matrix.folder }} apply -auto-approve


  install-tools:
    name: Install Kyverno and Velero
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Install Kyverno
      run: sh script/kyverno.sh


      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      continue-on-error: true # Continue even if there are apply errors
