name: Terraform Apply

on:
  push:
    branches:
    - main # Change this to your main branch name if different

jobs:
  terraform_apply_eks:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: Initialize and apply Terraform
      run: |
        terraform init
        terraform apply --auto-approve


      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

