name: Terraform Apply

on:
  push:
    branches:
    - main # Change this to your main branch name if different

jobs:
  terraform_apply_eks:
    name: Terraform VPC And EKS
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2 # Change to your AWS region

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: Initialize and apply Terraform
      run: |
      
        terraform destroy
