name: Terraform Apply

on:
  push:
    branches:
    - main # Change this to your main branch name if different
permissions:
  id-token: write
  contents: read

jobs:
  terraform_apply_eks:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: Initialize and apply Terraform
      run: |
        terraform init
        terraform apply --auto-approve


